# Generated by Django 6.0.3 on 2026-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("growth", "Growth"),
                    ("enterprise", "Enterprise"),
                    ("basic", "Basic"),
                    ("active_agent", "Active Agent"),
                    ("top_producer", "Top Producer"),
                    ("landlord_basic", "Landlord Basic"),
                    ("landlord_pro", "Landlord Pro"),
                    ("standard", "Standard"),
                    ("vip_hunter", "VIP Hunter"),
                ],
                default="starter",
                max_length=30,
            ),
        ),
    ]
