# Generated by Django 5.2.7 on 2025-11-21 15:30

import agents.models
import django.db.models.deletion
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('profile_name', models.CharField(default='No Name', max_length=100, verbose_name='Full Name')),
                ('agent_uuid', models.CharField(max_length=36, unique=True, verbose_name='Agent uuid')),
                ('company_uuid', models.CharField(blank=True, default='Unemployed', max_length=36, verbose_name='Company uuid')),
                ('universal_agent', models.BooleanField(default=False, verbose_name='Universal agent')),
                ('phone_number', models.CharField(default='None', max_length=12, verbose_name='Phone.No')),
                ('email', models.EmailField(blank=True, default='None', max_length=100, verbose_name='Email')),
                ('location', models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos', verbose_name='Base City')),
                ('language', models.CharField(default='English', verbose_name='language Spoken')),
                ('bio', models.TextField(default='No Profile', verbose_name='Work Summary')),
                ('work_type', models.CharField(default='None', verbose_name='Nature of work')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=agents.models.agent_picture_path, validators=[core.validators.validate_image], verbose_name='Profile Picture')),
                ('government_id', models.FileField(blank=True, null=True, upload_to='agent/ID', validators=[core.validators.validate_file], verbose_name='Government ID')),
                ('certificate', models.FileField(blank=True, upload_to='', verbose_name='Professional Certificate')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified agent')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('title', models.CharField(max_length=100, verbose_name='Position')),
                ('past_experence', models.CharField(max_length=100, verbose_name='Experience')),
                ('start_date', models.DateField(verbose_name='Started')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ended')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='agents.agentinformation')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.CharField(choices=[('0-1', '0-1'), ('1-3', '1-3'), ('3-5', '3-5'), ('5-10', '5-10'), ('10+', '10+')], default='0-1', verbose_name='Years Of Experience')),
                ('agency', models.BooleanField(default=False, verbose_name='Affiliated With Agency?')),
                ('agency_name', models.CharField(default='Not With Agency', max_length=50, verbose_name='Agency Name')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universal', to='agents.agentinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_platform', models.CharField(choices=[('X', 'X'), ('linkedin', 'linkedin'), ('Instagram', 'Instagram'), ('Company Website', 'Company Website'), ('Other', 'Other')], default='Instagram', max_length=20)),
                ('link_to_social', models.URLField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='agents.agentinformation')),
            ],
            options={
                'unique_together': {('social_platform', 'link_to_social')},
            },
        ),
    ]
