# Generated by Django 5.2.7 on 2025-11-21 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinformation',
            name='agent_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Agent uuid'),
        ),
    ]

