# Generated by Django 5.2.7 on 2025-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agentinformation_agent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinformation',
            name='bio',
            field=models.TextField(verbose_name='Work Summary'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Professional Certificate'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='company_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Company uuid'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='language',
            field=models.CharField(max_length=100, verbose_name='language Spoken'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='location',
            field=models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], verbose_name='Base City'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Phone.No'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='profile_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='work_type',
            field=models.CharField(max_length=100, verbose_name='Nature of work'),
        ),
    ]
