# Generated by Django 5.2.7 on 2025-11-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentinformation_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='link_to_social',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social_platform',
            field=models.CharField(blank=True, choices=[('X', 'X'), ('linkedin', 'linkedin'), ('Instagram', 'Instagram'), ('Other', 'Other')], default='Instagram', max_length=20),
        ),
    ]
