# Generated by Django 5.2.7 on 2025-11-22 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_sociallinks_link_to_social_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallinks',
            unique_together=set(),
        ),
    ]
