# Generated by Django 5.2.7 on 2025-12-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_sociallinks_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_views', models.IntegerField(default=0, verbose_name='Total No of views on properties')),
                ('profile_views', models.IntegerField(blank=True, default=0, verbose_name='Companies That viewed your profile')),
                ('ratings', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Agents Rating')),
                ('reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Reviews')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='agents.agentinformation')),
            ],
        ),
    ]

