# Generated by Django 5.2.7 on 2026-01-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentinformation_users_alter_agentinformation_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentanalytics',
            name='listing_views',
        ),
    ]

