# Generated by Django 5.2.7 on 2026-01-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_agentanalytics_listing_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=None, verbose_name='Users Session ID')),
                ('inquires_check', models.IntegerField(default=0, verbose_name='inq')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_id', to='agents.agentinformation')),
            ],
        ),
    ]

