# Generated by Django 5.2.7 on 2026-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinformation',
            name='bio',
            field=models.TextField(max_length=250, verbose_name='Work Summary'),
        ),
    ]

