# Generated by Django 5.2.7 on 2026-01-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentinformation_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='profile_name',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=70, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Position'),
        ),
    ]
