# Generated by Django 5.2.7 on 2026-01-23 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agentinformation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentanalytics',
            name='average_lease_views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Average Lease Views'),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='average_profile_views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Average Profile Views'),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='average_sale_views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Average Sale Views'),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='competition',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Engagement Score'),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Reset Date'),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='property_views_l',
            field=models.IntegerField(blank=True, default=0, verbose_name='Lease Property Views'),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='property_views_s',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sale Property Views'),
        ),
        migrations.AlterField(
            model_name='agentanalytics',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='agents.agentinformation'),
        ),
        migrations.AlterField(
            model_name='agentanalytics',
            name='profile_views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Profile Views'),
        ),
        migrations.AlterField(
            model_name='agentanalytics',
            name='ratings',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Agent Rating'),
        ),
    ]
