# Generated by Django 5.2.7 on 2026-01-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='link_to_social',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social_platform',
            field=models.CharField(choices=[('X', 'X'), ('linkedin', 'linkedin'), ('Instagram', 'Instagram'), ('Other', 'Other')], max_length=20),
        ),
    ]
