# Generated by Django 5.2.7 on 2026-01-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_alter_sociallinks_link_to_social_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversalAgent',
        ),
    ]
