# Generated by Django 5.2.7 on 2026-01-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_delete_universalagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinformation',
            name='bio',
            field=models.TextField(max_length=1024, verbose_name='About You?'),
        ),
    ]

