# Generated by Django 6.0.3 on 2026-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_alter_agentinformation_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinformation',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='agentinformation',
            name='first_name',
            field=models.CharField(default='Victor', max_length=50, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='agentinformation',
            name='last_name',
            field=models.CharField(default='Akinfiresoye', max_length=50, verbose_name='Last Name'),
        ),
    ]

