# Generated by Django 6.0.3 on 2026-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_remove_agentinformation_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinformation',
            name='first_name',
            field=models.CharField(default='Unspecified', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='last_name',
            field=models.CharField(default='j', max_length=50, verbose_name='Last Name'),
        ),
    ]
