# Generated by Django 6.0.3 on 2026-03-18 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_alter_agentinformation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinformation',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]

