# Generated by Django 6.0.3 on 2026-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_agentinformation_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinformation',
            name='inventory_slot',
            field=models.IntegerField(default=10, verbose_name='Inventory Slots'),
        ),
        migrations.AddField(
            model_name='agentinformation',
            name='listing_slots',
            field=models.IntegerField(default=6, verbose_name='Listing Slots'),
        ),
    ]
