# Generated by Django 6.0.3 on 2026-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_agentinformation_inventory_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentanalytics',
            name='average_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='average_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='monthly_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentanalytics',
            name='monthly_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
