# Generated by Django 6.0.3 on 2026-03-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_agentanalytics_average_leads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinformation',
            name='universal_agent',
        ),
    ]
