# Generated by Django 6.0.3 on 2026-04-05 20:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_remove_agentinformation_universal_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinformation',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='agent/certificates', validators=[core.validators.validate_file], verbose_name='Professional Certificate'),
        ),
        migrations.AlterField(
            model_name='agentinformation',
            name='company_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='Company uuid'),
        ),
    ]
