# Generated by Django 6.0.3 on 2026-04-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0024_remove_agentinformation_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinformation",
            name="agent_tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("active", "Active Agent"),
                    ("producer", "Top Producer"),
                ],
                default="active",
                verbose_name="Agent Tier",
            ),
        ),
        migrations.AlterField(
            model_name="agentinformation",
            name="inventory_slot",
            field=models.IntegerField(default=30, verbose_name="Inventory Slots"),
        ),
        migrations.AlterField(
            model_name="agentinformation",
            name="listing_slots",
            field=models.IntegerField(default=15, verbose_name="Listing Slots"),
        ),
    ]
