# Generated by Django 6.0.3 on 2026-04-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0025_agentinformation_agent_tier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentinformation",
            name="agent_tier",
        ),
        migrations.RemoveField(
            model_name="agentinformation",
            name="inventory_slot",
        ),
        migrations.RemoveField(
            model_name="agentinformation",
            name="listing_slots",
        ),
    ]
