# Generated by Django 5.2.7 on 2025-11-22 17:14

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('feedback', models.CharField(max_length=300)),
                ('date_sent', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManagementRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='Landlord')),
                ('owner', models.CharField(default='Akinfiresoye', max_length=120, verbose_name='Listed By')),
                ('company_uuid', models.CharField(blank=True, default='None', max_length=36, verbose_name='Company')),
                ('agent_uuid', models.CharField(blank=True, default='None', max_length=36, verbose_name='Agent')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('state', models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos State', max_length=20)),
                ('phone_number', models.CharField(verbose_name='Phone Number')),
                ('price_range', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('available', models.BooleanField(default=True, verbose_name='Availble')),
                ('bedrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('bathrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('size', models.IntegerField(blank=True, default=0, verbose_name='size')),
                ('parking_spaces', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('whilist', models.BooleanField(default=False, verbose_name='Add to Whilist')),
                ('compare', models.BooleanField(default=False, verbose_name='Compare')),
                ('house_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Block of flats', 'Block of Flats'), ('Bungalow Design', 'Bungalow Design'), ('Conclusion', 'Conclusion'), ('Detached bungalow', 'Detached Bungalow'), ('Detached duplex', 'Detached Duplex'), ('Duplex', 'Duplex'), ('Detached houses', 'Detached Houses'), ('Duplex Design', 'Duplex Design'), ('Detached', 'Detached'), ('Detached House', 'Detached House'), ('Massionette', 'Masionette'), ('Mansion', 'Mansion'), ('Penthouse', 'Penthouse'), ('Semi detached duplex', 'Semi Detached Duplex'), ('Semi detached bungalow', 'Semi Detached Bungalow'), ('Terraced bungalow', 'Terraced Bungalow'), ('Terraced duplex', 'Terraced Duplexes'), ('Townhouse', 'Townhouse'), ('Terraced houses', 'Terraced houses'), ('Traditional houses', 'Traditional Houses'), ('Terrace', 'Terrace')], default='Bungalow', max_length=30)),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='images/rent', validators=[core.validators.validate_image])),
                ('listed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('time_stamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('property_type', models.CharField(default='Rent', verbose_name='property Type')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManagementSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='Landlord')),
                ('company_uuid', models.CharField(blank=True, default='None', max_length=40, verbose_name='Company')),
                ('agent_uuid', models.CharField(blank=True, default='None', max_length=36, verbose_name='Agent')),
                ('property_description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('state', models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos', max_length=20)),
                ('phone_number', models.CharField(verbose_name='Phone Number')),
                ('owner', models.CharField(max_length=120, verbose_name='Listed By')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('bedrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('bathrooms', models.IntegerField(blank=True, default=1, null=True)),
                ('parking_spaces', models.IntegerField(default=0)),
                ('size', models.IntegerField(blank=True, default=0, verbose_name='size')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('whilist', models.BooleanField(default=False, verbose_name='Add to Whilist')),
                ('compare', models.BooleanField(default=False, verbose_name='Compare')),
                ('house_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Block of flats', 'Block of Flats'), ('Bungalow Design', 'Bungalow Design'), ('Conclusion', 'Conclusion'), ('Detached bungalow', 'Detached Bungalow'), ('Detached duplex', 'Detached Duplex'), ('Duplex', 'Duplex'), ('Detached houses', 'Detached Houses'), ('Duplex Design', 'Duplex Design'), ('Detached', 'Detached'), ('Detached House', 'Detached House'), ('Massionette', 'Masionette'), ('Mansion', 'Mansion'), ('Penthouse', 'Penthouse'), ('Semi detached duplex', 'Semi Detached Duplex'), ('Semi detached bungalow', 'Semi Detached Bungalow'), ('Terraced bungalow', 'Terraced Bungalow'), ('Terraced duplex', 'Terraced Duplexes'), ('Townhouse', 'Townhouse'), ('Terraced houses', 'Terraced houses'), ('Traditional houses', 'Traditional Houses'), ('Terrace', 'Terrace')], default='Bungalow', max_length=30)),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='images/buy', validators=[core.validators.validate_image])),
                ('listed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('time_stamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('property_type', models.CharField(default='Sale', verbose_name='property Type')),
                ('negotiate', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManagementRentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=None, verbose_name='user_id')),
                ('inquires_check', models.IntegerField(default=None, verbose_name='Inquiries')),
                ('on_lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_analytics', to='core.propertymanagementrent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManagementSaleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=None, verbose_name='user_id')),
                ('inquires_check', models.IntegerField(default=None, verbose_name='Inquiries')),
                ('on_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_analytics', to='core.propertymanagementsale')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_images', models.ImageField(blank=True, null=True, upload_to='images/rent', validators=[core.validators.validate_image])),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.propertymanagementrent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_images', models.ImageField(blank=True, null=True, upload_to='images/buy', validators=[core.validators.validate_image])),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.propertymanagementsale')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='core.propertymanagementrent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WishlistForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='core.propertymanagementsale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'user')},
            },
        ),
    ]

