# Generated by Django 5.2.7 on 2025-11-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='owner',
            field=models.CharField(max_length=120, verbose_name='Listed By'),
        ),
    ]
