# Generated by Django 5.2.7 on 2025-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_propertymanagementrent_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='total_likes',
            field=models.IntegerField(default=0, verbose_name='Wishlisted time'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='total_likes',
            field=models.IntegerField(default=0, verbose_name='Wishlisted time'),
        ),
    ]

