# Generated by Django 5.2.7 on 2025-12-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propertymanagementrent_total_likes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistforrent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistforsale',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='whilist',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='whilist',
        ),
        migrations.AddField(
            model_name='wishlistforrent',
            name='users_id',
            field=models.IntegerField(default=1, verbose_name='User In question'),
        ),
        migrations.AddField(
            model_name='wishlistforrent',
            name='whilist',
            field=models.BooleanField(default=False, verbose_name='Add to Whilist'),
        ),
        migrations.AddField(
            model_name='wishlistforsale',
            name='users_id',
            field=models.IntegerField(default=1, verbose_name='User In question'),
        ),
        migrations.AddField(
            model_name='wishlistforsale',
            name='whilist',
            field=models.BooleanField(default=False, verbose_name='Add to Whilist'),
        ),
        migrations.AlterField(
            model_name='wishlistforrent',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_rent', to='core.propertymanagementrent'),
        ),
        migrations.RemoveField(
            model_name='wishlistforrent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlistforsale',
            name='user',
        ),
    ]

