# Generated by Django 5.2.7 on 2025-12-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wishlistforrent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistforsale',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_sale', to='core.propertymanagementsale'),
        ),
    ]

