# Generated by Django 5.2.7 on 2025-12-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wishlistforsale_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistStorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='Owner Of Wishlist')),
                ('property_id', models.IntegerField(default=1, verbose_name='Property In Question')),
                ('property_type', models.CharField(default='Rent', verbose_name='Property_type')),
            ],
        ),
    ]

