# Generated by Django 5.2.7 on 2025-12-08 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wishliststorageunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistforsale',
            name='property',
        ),
        migrations.DeleteModel(
            name='WishlistForRent',
        ),
        migrations.DeleteModel(
            name='WishlistForSale',
        ),
    ]
