# Generated by Django 5.2.7 on 2025-12-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_propertymanagementrent_compare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='commercial',
            field=models.CharField(blank=True, choices=[('Office Space', 'Office Space'), ('Co-Working Space', 'Co-Working Space'), ('Serviced Offices', 'Co-Working Space'), ('Corperate Buildings', 'Corperate Buildings'), ('Buisness Centers', 'Buisness Centers'), ('Shops', 'Shops'), ('Retail Spaces', 'Retail Spaces'), ('Shopping Complexes', 'Shopping Complexes'), ('Malls', 'Malls'), ('Showrooms', 'Showrooms'), ('Event Halls', 'Event Halls'), ('Conference Centers', 'Conference Centers'), ('Hotels', 'Hotels'), ('Guest Houses', 'Guest Houses')], default='Office Space', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='lands',
            field=models.CharField(blank=True, choices=[('Residential land', 'Residential land'), ('Commercial land', 'Commercial land'), ('Industrial land', 'Industrial land'), ('Mixed-use land', 'Mixed-use land'), ('Plots', 'Plots'), ('Acres/Hectares', 'Acres/Hectares'), ('Dry Land', 'Dry Land'), ('Swampy land', 'Swampy land'), ('Waterfront land', 'Waterfront land'), ('Beachfront land', 'Beachfront land'), ('Farmland', 'Farmland'), ('Agricultural land', 'Agricultural land'), ('Estate Plot', 'Estate Plot')], default='Farmland', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='price_range',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='residential',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Block of flats', 'Block of Flats'), ('Bungalow Design', 'Bungalow Design'), ('Conclusion', 'Conclusion'), ('Detached bungalow', 'Detached Bungalow'), ('Detached duplex', 'Detached Duplex'), ('Duplex', 'Duplex'), ('Detached houses', 'Detached Houses'), ('Duplex Design', 'Duplex Design'), ('Detached', 'Detached'), ('Detached House', 'Detached House'), ('Gated estate houses', 'Gated estate houses'), ('Luxury homes', 'Luxury homes'), ('Massionette', 'Masionette'), ('Mansion', 'Mansion'), ('Mini Flat', 'Mini Flat'), ('Penthouse', 'Penthouse'), ('Semi detached duplex', 'Semi Detached Duplex'), ('Semi detached bungalow', 'Semi Detached Bungalow'), ('Self-contained apartments', 'Self-contained apartments'), ('Studio apartments', 'Studio apartments'), ('Serviced apartments', 'Serviced apartments'), ('Smart homes', 'Smart homes'), ('Terraced bungalow', 'Terraced Bungalow'), ('Terraced duplex', 'Terraced Duplexes'), ('Townhouse', 'Townhouse'), ('Terraced houses', 'Terraced houses'), ('Traditional houses', 'Traditional Houses'), ('Terrace', 'Terrace')], default='Apartment', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
