# Generated by Django 5.2.7 on 2025-12-16 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_propertymanagementsale_commercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='Users ID')),
                ('property_type', models.CharField(default='Rent', verbose_name='Property Type')),
                ('property_id', models.IntegerField(default=1, verbose_name='Property Viewed')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertymanagementsaleanalytics',
            name='on_sale',
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='property_category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Land', 'Plot/Land')], default='Residential'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='property_category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Land', 'Plot/Land')], default='Residential'),
        ),
        migrations.DeleteModel(
            name='PropertyManagementRentAnalytics',
        ),
        migrations.DeleteModel(
            name='PropertyManagementSaleAnalytics',
        ),
    ]
