# Generated by Django 5.2.7 on 2025-12-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_propertyviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyviews',
            name='time_stamp',
        ),
        migrations.AlterField(
            model_name='propertyviews',
            name='property_id',
            field=models.IntegerField(default=1, verbose_name='Property ID Viewed'),
        ),
    ]

