# Generated by Django 5.2.7 on 2025-12-29 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_propertyviews_time_stamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_uuid', models.CharField(blank=True, default=None, null=True, verbose_name='Company UUID')),
                ('agent_uuid', models.CharField(blank=True, default=None, null=True, verbose_name='Agents UUID')),
                ('appointment', models.DateField(default=django.utils.timezone.now, verbose_name='Appointment')),
                ('note', models.CharField(blank=True, default='No Note Provided', null=True, verbose_name='Appointment Note')),
                ('appointment_type', models.CharField(choices=[('Client', 'Client'), ('Personal', 'Personal'), ('Company', 'Company')], default='Personal', verbose_name='Appointment type')),
                ('property_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='Property ID')),
                ('property_type', models.CharField(blank=True, default=None, null=True, verbose_name='Property Type')),
            ],
        ),
    ]

