# Generated by Django 5.2.7 on 2025-12-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='lead_uuid',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Lead UUID'),
        ),
    ]
