# Generated by Django 5.2.7 on 2026-01-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_appointments_lead_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal'), ('Virtual', 'Virtual')], default='Personal', verbose_name='Appointment type'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='commercial',
            field=models.CharField(blank=True, choices=[('Office Space', 'Office Space'), ('Co-Working Space', 'Co-Working Space'), ('Serviced Offices', 'Co-Working Space'), ('Corperate Buildings', 'Corperate Buildings'), ('Business Centers', 'Business Centers'), ('Shops', 'Shops'), ('Retail Spaces', 'Retail Spaces'), ('Shopping Complexes', 'Shopping Complexes'), ('Malls', 'Malls'), ('Showrooms', 'Showrooms'), ('Event Halls', 'Event Halls'), ('Conference Centers', 'Conference Centers'), ('Hotels', 'Hotels'), ('Guest Houses', 'Guest Houses')], default='Office Space', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='commercial',
            field=models.CharField(blank=True, choices=[('Office Space', 'Office Space'), ('Co-Working Space', 'Co-Working Space'), ('Serviced Offices', 'Co-Working Space'), ('Corperate Buildings', 'Corperate Buildings'), ('Business Centers', 'Business Centers'), ('Shops', 'Shops'), ('Retail Spaces', 'Retail Spaces'), ('Shopping Complexes', 'Shopping Complexes'), ('Malls', 'Malls'), ('Showrooms', 'Showrooms'), ('Event Halls', 'Event Halls'), ('Conference Centers', 'Conference Centers'), ('Hotels', 'Hotels'), ('Guest Houses', 'Guest Houses')], default='Office Space', max_length=30),
        ),
    ]
