# Generated by Django 5.2.7 on 2026-01-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_appointments_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyviews',
            name='uuid',
            field=models.CharField(default='da5dac64-3448-48a7-a209-4c84010d9ad2', verbose_name='UUID'),
        ),
    ]

