# Generated by Django 5.2.7 on 2026-01-20 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_propertyviews_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('a224b968-3c31-4790-8fb3-79bd75d0a6ce'), unique=True, verbose_name='UUID'),
        ),
    ]

