# Generated by Django 5.2.7 on 2026-01-20 22:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('264dca84-6e86-4198-8f40-b23d2b178df1'), unique=True, verbose_name='UUID'),
        ),
    ]

