# Generated by Django 5.2.7 on 2026-01-20 23:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('fc5c447e-c777-4de5-9fe9-e37e6d7fd5ab'), unique=True, verbose_name='UUID'),
        ),
    ]

