# Generated by Django 5.2.7 on 2026-01-23 22:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('5af99ab0-df23-481c-bbb9-bdc9ce1ba169'), unique=True, verbose_name='UUID'),
        ),
    ]

