# Generated by Django 5.2.7 on 2026-01-24 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('bdba79ea-41f1-4747-8570-b2a221d40e67'), unique=True, verbose_name='UUID'),
        ),
    ]

