# Generated by Django 5.2.7 on 2026-01-30 01:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('4f5fcae2-3283-4c13-9b1c-87c6cbf03830'), unique=True, verbose_name='UUID'),
        ),
    ]
