# Generated by Django 5.2.7 on 2026-01-30 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('e4d2cf72-c185-4a07-bc69-7d8f190cbd90'), unique=True, verbose_name='UUID'),
        ),
    ]
