# Generated by Django 5.2.7 on 2026-01-30 02:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('6e66119e-8ba8-45f7-bcf2-371ed13fac41'), unique=True, verbose_name='UUID'),
        ),
    ]
