# Generated by Django 5.2.7 on 2026-01-31 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('280de073-af6a-4f43-a178-2179c6aae139'), unique=True, verbose_name='UUID'),
        ),
    ]
