# Generated by Django 5.2.7 on 2026-01-31 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('c6f57ad9-cf01-49ef-81a3-7030aa77547c'), unique=True, verbose_name='UUID'),
        ),
    ]

