# Generated by Django 5.2.7 on 2026-01-31 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('7d245a4f-bb24-41e8-941a-2f0b2a453e19'), unique=True, verbose_name='UUID'),
        ),
    ]
