# Generated by Django 5.2.7 on 2026-03-13 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('6545f753-8109-4f6e-94cf-762d44dab588'), unique=True, verbose_name='UUID'),
        ),
    ]
