# Generated by Django 5.2.7 on 2026-03-13 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('bbc0a07b-a457-4250-9498-78d3fd298783'), unique=True, verbose_name='UUID'),
        ),
    ]

