# Generated by Django 6.0.3 on 2026-03-14 13:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_appointments_appointment_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Your Email')),
                ('feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('date_sent', models.DateField(default=django.utils.timezone.now)),
                ('role', models.CharField(blank=True, choices=[('agent', 'Agent'), ('company', 'Company Admin'), ('admin', 'Admin'), ('landlord', 'Landlord')], max_length=10, null=True)),
                ('reaction', models.PositiveSmallIntegerField(blank=True, help_text='Emoji reaction score from 1 (worst) to 5 (best)', null=True)),
                ('category', models.CharField(blank=True, choices=[('bug', 'Bug Report'), ('feature', 'Feature Idea'), ('complaint', 'Complaint'), ('praise', 'Praise')], max_length=10, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('891005b5-952b-45d6-a7e5-034c3f1859bd'), unique=True, verbose_name='UUID'),
        ),
    ]

