# Generated by Django 6.0.3 on 2026-03-14 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_feedbacks_delete_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('3682e53d-62f9-41ad-9d62-9a038067ce6f'), unique=True, verbose_name='UUID'),
        ),
    ]

