# Generated by Django 6.0.3 on 2026-03-15 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('5084e28a-93b0-4ab4-8c5a-af41868fd866'), unique=True, verbose_name='UUID'),
        ),
    ]
