# Generated by Django 6.0.3 on 2026-03-16 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('58cbca02-c722-4c66-9113-498b1200b14a'), unique=True, verbose_name='UUID'),
        ),
    ]

