# Generated by Django 6.0.3 on 2026-03-16 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('90018bf6-6adb-4e65-99f2-2884ea02b758'), unique=True, verbose_name='UUID'),
        ),
    ]
