# Generated by Django 6.0.3 on 2026-03-17 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('34ce2545-89f4-4f3f-ac3d-6175ba9898ac'), unique=True, verbose_name='UUID'),
        ),
    ]
