# Generated by Django 6.0.3 on 2026-03-17 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('e3da631b-e79b-4780-955b-7c4c6784c832'), unique=True, verbose_name='UUID'),
        ),
    ]

