# Generated by Django 6.0.3 on 2026-03-17 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('f01a76c2-e4a7-425e-b651-f521b163ad4e'), unique=True, verbose_name='UUID'),
        ),
    ]

