# Generated by Django 6.0.3 on 2026-03-18 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('7c8d239d-ee64-4a8d-8b84-d6050295b5eb'), unique=True, verbose_name='UUID'),
        ),
    ]

