# Generated by Django 6.0.3 on 2026-03-18 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='featured_listings',
            field=models.BooleanField(default=False, verbose_name='Featured Lising'),
        ),
        migrations.AddField(
            model_name='propertymanagementrent',
            name='listing_score',
            field=models.IntegerField(default=0, verbose_name='Listing Score'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='featured_listings',
            field=models.BooleanField(default=False, verbose_name='Featured Lising'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='listing_score',
            field=models.IntegerField(default=0, verbose_name='Listing Score'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('1ae04ad7-4618-4b07-8861-28376b0f276a'), unique=True, verbose_name='UUID'),
        ),
    ]

