# Generated by Django 6.0.3 on 2026-03-19 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_propertymanagementrent_featured_listings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Property Focus Areas',
            },
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('ab2a3635-4a10-47d8-a299-d0ad317ea711'), unique=True, verbose_name='UUID'),
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_type', models.CharField(blank=True, choices=[('Real Estate Agency', 'Real Estate Agency'), ('Startup', 'Fast-Grwoing Startup'), ('Property Developer', 'Property Developer'), ('Investmentn Firm', 'Investment Firm'), ('other', 'Other')], default='other', verbose_name='Company Type')),
                ('years_in_buisness', models.CharField(blank=True, choices=[('Less than 1 year', 'Less than 1 year'), ('1-3 years', '1-3 years'), ('3-5 years', '3-5 years'), ('5-10 years', '5-10 years'), ('10+ years', '10+ years')], default='Less than 1 year', verbose_name='Years In Buisness')),
                ('team_size', models.CharField(blank=True, choices=[('1-5 People', '1-5 People'), ('6-20 People', '6-20 People'), ('21-50 People', '21-50 People'), ('50+ People', '50+ People')], default='1-5 People', verbose_name='Team Size')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
                ('city', models.CharField(default='Akure', max_length=20, verbose_name='City')),
                ('state', models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos', verbose_name='State')),
                ('person_of_contact', models.CharField(max_length=70, verbose_name='Full Name')),
                ('person_position', models.CharField(max_length=20, verbose_name='Position')),
                ('email', models.EmailField(max_length=50, verbose_name='Persons Email')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Persons Phone Number')),
                ('average_listings', models.CharField(blank=True, choices=[('1-10 listings', '1-10 listings'), ('11-25 listings', '11-25 listings'), ('26-50 listings', '26-50 listings'), ('51-100 listings', '26-100 listings'), ('100+ listings', '100+ listings')], default='1-10 listings', null=True, verbose_name='Mothly Listings')),
                ('annual_revenue', models.CharField(choices=[('Below ₦10 Million', 'Below ₦10 Million'), ('₦10M - ₦50M', '₦10M - ₦50M'), ('₦50M - ₦100M', '₦50M - ₦100M'), ('₦100M - ₦500M', '₦100M - ₦500M'), ('₦500M+', '₦500M+')], default='Below ₦10 Million', verbose_name='Annual Revenue')),
                ('growth_goals', models.CharField(blank=True, max_length=200, null=True, verbose_name='Growth Goals')),
                ('why_question', models.CharField(max_length=200, verbose_name='Why Partner with us')),
                ('partnership_benefits', models.ManyToManyField(blank=True, to='core.partnershipgoal')),
                ('property_types', models.ManyToManyField(blank=True, to='core.propertyfocus')),
            ],
        ),
    ]
