# Generated by Django 6.0.3 on 2026-03-21 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_seed_partnership_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='available',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='available',
        ),
        migrations.AddField(
            model_name='propertymanagementrent',
            name='is_listed',
            field=models.BooleanField(default=True, verbose_name='is_listed'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='is_listed',
            field=models.BooleanField(default=True, verbose_name='is_listed'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('dd0b3e82-ce79-482b-bad5-c432fad1d2c1'), unique=True, verbose_name='UUID'),
        ),
    ]

