# Generated by Django 6.0.3 on 2026-03-21 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_propertymanagementrent_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('1d059be9-75df-4ef4-bec6-ac02b86d546d'), unique=True, verbose_name='UUID'),
        ),
    ]

