# Generated by Django 6.0.3 on 2026-03-21 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('0846ffee-444c-4e7f-9c11-f2c6e8fa3034'), unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the property (Max 3,000 characters).', max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='property_description',
            field=models.TextField(blank=True, help_text='Detailed description of the property (Max 3,000 characters).', max_length=3000, verbose_name='Description'),
        ),
    ]
