# Generated by Django 6.0.3 on 2026-03-22 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_appointments_appointment_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('bcffd025-b58f-4581-ab4c-45b478fa76ad'), unique=True, verbose_name='UUID'),
        ),
    ]
