# Generated by Django 6.0.3 on 2026-03-22 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('018c2464-41bd-4695-a2c7-02b0e8ce859a'), unique=True, verbose_name='UUID'),
        ),
    ]

