# Generated by Django 6.0.3 on 2026-03-23 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('ff84187d-4b36-4a54-958a-e80f8ad86ae7'), unique=True, verbose_name='UUID'),
        ),
    ]
