# Generated by Django 6.0.3 on 2026-03-23 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('1f53a355-10e1-461d-a0d0-89921f253c74'), unique=True, verbose_name='UUID'),
        ),
    ]
