# Generated by Django 6.0.3 on 2026-03-23 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('45ff8e6b-d6e8-48df-992c-5468d4fff4af'), unique=True, verbose_name='UUID'),
        ),
    ]
