# Generated by Django 6.0.3 on 2026-03-25 13:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_errorlog_alter_appointments_appointment_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnership",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="partnership",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Agree"),
                    ("denied", "Deny"),
                ],
                default="pending",
                verbose_name="Partnership Status",
            ),
        ),
        migrations.AddField(
            model_name="propertymanagementrent",
            name="flagged",
            field=models.BooleanField(default=False, verbose_name="Flagged"),
        ),
        migrations.AddField(
            model_name="propertymanagementsale",
            name="flagged",
            field=models.BooleanField(default=False, verbose_name="Flagged"),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="appointment_uuid",
            field=models.CharField(
                default=uuid.UUID("ed4b1b73-7b52-4921-94bf-c566e3d1fb14"),
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
