# Generated by Django 6.0.3 on 2026-03-26 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_partnership_created_at_partnership_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('5d7fb477-6ad5-4d71-9be8-46753d85e0b2'), unique=True, verbose_name='UUID'),
        ),
        migrations.CreateModel(
            name='UsersLeaseFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField(verbose_name='Users Who Flagged')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_flags', to='core.propertymanagementrent')),
            ],
        ),
        migrations.CreateModel(
            name='UsersSaleFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField(verbose_name='Users Who Flagged')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_flags', to='core.propertymanagementsale')),
            ],
        ),
    ]
