# Generated by Django 6.0.3 on 2026-03-26 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_appointments_appointment_uuid_usersleaseflags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('8cf703aa-df65-42f0-b431-ab9ca13a217b'), unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='agent_uuid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='company_uuid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='agent_uuid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='Agent_uuid'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='company_uuid',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Company_uuid'),
        ),
    ]
