# Generated by Django 6.0.3 on 2026-03-26 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_appointments_appointment_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_uuid',
            field=models.CharField(default=uuid.UUID('3331f206-7b09-439a-aa79-177e4ba4ddf7'), unique=True, verbose_name='UUID'),
        ),
    ]
