# Generated by Django 6.0.3 on 2026-03-27 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_appointments_appointment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="appointment_uuid",
            field=models.CharField(
                default=uuid.UUID("0faaf9a0-840e-4f1b-aae8-9761e2ec510f"),
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
