# Generated by Django 6.0.3 on 2026-03-30 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_appointments_appointment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="appointment_uuid",
            field=models.CharField(
                default=uuid.UUID("aeb4a724-b669-4618-9599-77f41ce2e412"),
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
