# Generated by Django 6.0.3 on 2026-03-30 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_alter_appointments_appointment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="appointment_uuid",
            field=models.CharField(
                default=uuid.UUID("5f5fba70-3b8e-4312-acbc-89a96f77ea9a"),
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
