# Generated by Django 6.0.3 on 2026-03-30 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_appointments_appointment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="appointment_uuid",
            field=models.CharField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
    ]
