# Generated by Django 6.0.3 on 2026-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_appointments_appointment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='landlord_uuid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='Landlord_uuid'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='landlord_uuid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='Landlord_uuid'),
        ),
    ]
