# Generated by Django 6.0.3 on 2026-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_propertymanagementrent_landlord_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="landlord_uuid",
            field=models.CharField(
                blank=True, default=None, null=True, verbose_name="Landlord UUID"
            ),
        ),
    ]
