# Generated by Django 6.0.3 on 2026-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_appointments_landlord_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertymanagementrent",
            name="size",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="size"
            ),
        ),
        migrations.AlterField(
            model_name="propertymanagementsale",
            name="size",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="size"
            ),
        ),
    ]
