# Generated by Django 6.0.3 on 2026-04-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_propertymanagementrent_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymanagementrent",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertymanagementsale",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
