# Generated by Django 6.0.3 on 2026-04-05 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_propertymanagementrent_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='agent_uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=36, null=True, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='company_uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=36, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='featured_listings',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Featured Lising'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Flagged'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is_listed'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='listed_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='listing_score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Listing Score'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='agent_uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=36, null=True, verbose_name='Agent_uuid'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='company_uuid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=40, null=True, verbose_name='Company_uuid'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='featured_listings',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Featured Lising'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Flagged'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is_listed'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='listed_date',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='listing_score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Listing Score'),
        ),
    ]
