# Generated by Django 6.0.3 on 2026-04-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_wishliststorageunit_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointments",
            name="user",
        ),
    ]
