# Generated by Django 6.0.3 on 2026-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_propertymanagementrent_rent_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertymanagementrent",
            name="rent_rate",
            field=models.CharField(
                choices=[
                    ("Yearly", "Per Annum (Yearly)"),
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly (3 Months)"),
                    ("Bi-Annually", "Bi-Annually (6 Months)"),
                ],
                default="yearly",
                max_length=30,
            ),
        ),
    ]
