# Generated by Django 6.0.3 on 2026-04-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_propertymanagementrent_rent_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishliststorageunit",
            name="owner",
        ),
    ]
