# Generated by Django 6.0.3 on 2026-04-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_remove_wishliststorageunit_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, verbose_name="Persons Email"),
                ),
            ],
        ),
    ]
