# Generated by Django 6.0.3 on 2026-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_waitlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="propertymanagementrent",
            name="property_features",
            field=models.ManyToManyField(blank=True, to="core.propertyfeatures"),
        ),
        migrations.AddField(
            model_name="propertymanagementsale",
            name="property_features",
            field=models.ManyToManyField(blank=True, to="core.propertyfeatures"),
        ),
    ]
