# Generated by Django 6.0.3 on 2026-05-02 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_propertyfeatures_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlaggedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="Customer", max_length=10)),
                ("report_from", models.CharField(max_length=50)),
                (
                    "report_from_role",
                    models.CharField(default="Customer", max_length=10),
                ),
                ("report_count", models.IntegerField(default=1)),
                (
                    "report_reason",
                    models.CharField(
                        choices=[
                            ("Fraud/Scam", "Fraud/Scam activity"),
                            (
                                "Fake listings",
                                "Fake Listings or Misleading information",
                            ),
                            (
                                "Impersonation",
                                "Impersonation(pretending to be someone else)",
                            ),
                            (
                                "Harassment or abusive behavior",
                                "Harassment or abusive behavior",
                            ),
                            ("Spam", "Spam"),
                            ("Inappropirate content", "Inappropirate Content"),
                            (
                                "Failure to deliver agreed service",
                                "Failure to deliver agreed service",
                            ),
                            ("Suspicious activity", "Suspicious activity"),
                            (
                                "Violation of Platform rules",
                                "Violation of Platform rules",
                            ),
                            (
                                "Unverified/Illegal Properties",
                                "Unverified/Illegal Properties",
                            ),
                            (
                                "Hidden Charges/Unclear Pricing",
                                "Hidden Charges/Unclear Pricing",
                            ),
                            ("other", "other"),
                        ],
                        default="other",
                    ),
                ),
                (
                    "more_reason",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "time_reported",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
