# Generated by Django 6.0.3 on 2026-05-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_flaggedusers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flaggedusers",
            name="report_from",
        ),
    ]
