# Generated by Django 6.0.3 on 2026-05-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_remove_flaggedusers_report_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flaggedusers",
            name="user",
        ),
        migrations.AddField(
            model_name="flaggedusers",
            name="user_reported",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
