# Generated by Django 6.0.3 on 2026-10-08 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_remove_flaggedusers_user_flaggedusers_user_reported"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flaggedusers",
            name="report_count",
        ),
        migrations.CreateModel(
            name="PropertyInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_type", models.CharField(max_length=10)),
                ("property_id", models.IntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("save", "Saved"),
                            ("inquire", "Inquired"),
                            ("hide", "Hid"),
                            ("recommend_click", "Clicked a recommendation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "action", "-created_at"],
                        name="core_proper_user_id_11deeb_idx",
                    )
                ],
            },
        ),
    ]
