# Generated by Django 6.0.3 on 2026-10-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_remove_flaggedusers_report_count_propertyinteraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_type", models.CharField(default="Sale", max_length=10)),
                ("state_recomendations", models.JSONField(blank=True, default=list)),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        null=True,
                    ),
                ),
                ("average_beds", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "average_bathrooms",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("recomended_category", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="RecommendedProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_type", models.CharField(default="Sale", max_length=10)),
                ("property_id", models.IntegerField()),
                (
                    "recommendation_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="propertyinteraction",
            index=models.Index(
                fields=["user", "property_id"], name="core_proper_user_id_22e237_idx"
            ),
        ),
        migrations.AddField(
            model_name="recommendationdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recommendedproperties",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationdata",
            unique_together={("user", "property_type")},
        ),
        migrations.AddIndex(
            model_name="recommendedproperties",
            index=models.Index(
                fields=["user", "-recommendation_score"],
                name="core_recomm_user_id_776568_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendedproperties",
            constraint=models.UniqueConstraint(
                fields=("user", "property_type", "property_id"),
                name="uniq_user_recommended_property",
            ),
        ),
    ]
