# Generated by Django 5.2.6 on 2025-09-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0024_alter_propertymanagementsale_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='phone_number',
            field=models.CharField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='phone_number',
            field=models.CharField(verbose_name='Phone Number'),
        ),
    ]
