# Generated by Django 6.0.3 on 2026-03-30 15:00

import core.validators
import django.db.models.deletion
import django.utils.timezone
import landlord.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(default='Unspecified', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(default='Unspecified', max_length=50, verbose_name='Last Name')),
                ('landlord_uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Landlord uuid')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone.No')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('location', models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos', verbose_name='Base City')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=landlord.models.landlord_picture_path, validators=[core.validators.validate_image], verbose_name='Profile Picture')),
                ('government_id', models.FileField(blank=True, null=True, upload_to='landlord/ID', validators=[core.validators.validate_file], verbose_name='Government ID')),
                ('inventory_slots', models.IntegerField(default=3, verbose_name='Inventory Slots')),
                ('listing_slots', models.IntegerField(default=2, verbose_name='Listing Slots')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified landlord')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('users', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
