# Generated by Django 6.0.3 on 2026-04-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0002_remove_landlordinformation_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordinformation",
            name="landlord_tier",
            field=models.CharField(
                choices=[("basic", "Basic"), ("aggressive", "Aggressive Landlord")],
                default="aggressive",
            ),
        ),
    ]
