# Generated by Django 6.0.3 on 2026-04-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landlord", "0003_landlordinformation_landlord_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlordinformation",
            name="inventory_slots",
        ),
        migrations.RemoveField(
            model_name="landlordinformation",
            name="listing_slots",
        ),
    ]
