# Generated by Django 5.2.6 on 2025-09-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0022_alter_propertymanagementrent_price_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='phone_number',
            field=models.IntegerField(max_length=12, verbose_name='Phone Number'),
        ),
    ]
