# Generated by Django 5.2.6 on 2025-09-26 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0025_alter_propertymanagementrent_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('feedback', models.CharField(max_length=300)),
                ('date_sent', models.DateField(default=datetime.datetime(2025, 9, 26, 14, 3, 34, 101846))),
            ],
        ),
    ]
