# Generated by Django 5.2.6 on 2025-09-26 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0026_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_sent',
            field=models.DateField(default=datetime.datetime(2025, 9, 26, 13, 21, 54, 244340, tzinfo=datetime.timezone.utc)),
        ),
    ]
