# Generated by Django 5.2.6 on 2025-09-26 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0027_alter_feedback_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
