# Generated by Django 5.2.6 on 2025-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0028_alter_feedback_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='compare',
            field=models.BooleanField(default=False, verbose_name='Compare'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='compare',
            field=models.BooleanField(default=False, verbose_name='Compare'),
        ),
    ]
