# Generated by Django 5.2.6 on 2025-10-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0030_room_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist_for_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_by', models.IntegerField(default=1)),
                ('wishlist_r', models.BooleanField(default=False, verbose_name='Add to Whilist')),
                ('wishlist_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.propertymanagementrent')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist_for_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_by', models.IntegerField(default=1)),
                ('wishlist_s', models.BooleanField(default=False, verbose_name='Add to Whilist')),
                ('wishlist_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.propertymanagementsale')),
            ],
        ),
    ]
