# Generated by Django 5.2.6 on 2025-10-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0032_remove_wishlist_for_sale_wishlist_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='summary',
        ),
        migrations.AddField(
            model_name='propertymanagementrent',
            name='house_type',
            field=models.CharField(choices=[('Detached duplex', 'Detached Duplex'), ('Terraced duplex', 'Terraced Duplexes'), ('Semi detached duplex', 'Semi Detached Duplex'), ('Conclusion', 'Conclusion'), ('Townhouse', 'Townhouse'), ('Bungalow', 'Bungalow'), ('Detached bungalow', 'Detached Bungalow'), ('Block of flats', 'Block of Flats'), ('Semi detached bungalow', 'Semi Detached Bungalow'), ('Terraced bungalow', 'Terraced Bungalow'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse'), ('Detached houses', 'Detached Houses'), ('Terraced houses', 'Terraced houses'), ('Apartment', 'Apartment'), ('Traditional houses', 'Traditional Houses'), ('Mansion', 'Mansion'), ('Terrace', 'Terrace'), ('Duplex Design', 'Duplex Design'), ('Massionette', 'Masionette'), ('Bungalow Design', 'Bungalow Design'), ('Detached', 'Detached'), ('Detached House', 'Detached House')], default='Bungalow', max_length=30),
        ),
        migrations.AddField(
            model_name='propertymanagementrent',
            name='parking_spaces',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='house_type',
            field=models.CharField(choices=[('Detached duplex', 'Detached Duplex'), ('Terraced duplex', 'Terraced Duplexes'), ('Semi detached duplex', 'Semi Detached Duplex'), ('Conclusion', 'Conclusion'), ('Townhouse', 'Townhouse'), ('Bungalow', 'Bungalow'), ('Detached bungalow', 'Detached Bungalow'), ('Block of flats', 'Block of Flats'), ('Semi detached bungalow', 'Semi Detached Bungalow'), ('Terraced bungalow', 'Terraced Bungalow'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse'), ('Detached houses', 'Detached Houses'), ('Terraced houses', 'Terraced houses'), ('Apartment', 'Apartment'), ('Traditional houses', 'Traditional Houses'), ('Mansion', 'Mansion'), ('Terrace', 'Terrace'), ('Duplex Design', 'Duplex Design'), ('Massionette', 'Masionette'), ('Bungalow Design', 'Bungalow Design'), ('Detached', 'Detached'), ('Detached House', 'Detached House')], default='Bungalow', max_length=30),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='parking_spaces',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='price_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='summary',
            field=models.CharField(default=None, max_length=120, verbose_name='Short building tag'),
        ),
    ]
