# Generated by Django 5.2.6 on 2025-10-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0033_remove_propertymanagementrent_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='summary',
        ),
    ]
