# Generated by Django 5.2.6 on 2025-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0034_remove_propertymanagementsale_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='parking_spaces',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]

