# Generated by Django 5.2.7 on 2025-10-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0035_alter_propertymanagementsale_parking_spaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('professional_introduction', models.TextField(max_length=3000, verbose_name='Profile Introduction')),
                ('call_to_action', models.CharField(blank=True, max_length=50, verbose_name='CTA')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Professional First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Professional Last Name')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('title', models.CharField(max_length=100, verbose_name='Position')),
                ('past_experence', models.CharField(max_length=100, verbose_name='Experience')),
                ('start_date', models.DateField(verbose_name='Started')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ended')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='estate.agent_information')),
            ],
        ),
        migrations.AddField(
            model_name='agent_information',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='estate.userinformation'),
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_platform', models.CharField(choices=[('X', 'X'), ('Linkdin', 'Linkdin'), ('Instagram', 'Instagram'), ('Other', 'Other')], default='Instagram', max_length=20)),
                ('link_to_social', models.URLField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='estate.agent_information')),
            ],
            options={
                'unique_together': {('social_platform', 'link_to_social')},
            },
        ),
    ]
