# Generated by Django 5.2.7 on 2025-10-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0036_agent_information_userinformation_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_information',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
