# Generated by Django 5.2.7 on 2025-10-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0037_agent_information_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='propertymanagementrent',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='image6',
        ),
        migrations.CreateModel(
            name='PropertyRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_images', models.ImageField(blank=True, null=True, upload_to='images/rent')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.propertymanagementrent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_images', models.ImageField(blank=True, null=True, upload_to='images/buy')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.propertymanagementsale')),
            ],
        ),
    ]

