# Generated by Django 5.2.7 on 2025-10-23 22:24

import estate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0038_remove_propertymanagementrent_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent', validators=[estate.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy', validators=[estate.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='propertyrentimage',
            name='more_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/rent', validators=[estate.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='propertysaleimage',
            name='more_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/buy', validators=[estate.validators.validate_image]),
        ),
    ]
