# Generated by Django 5.2.7 on 2025-10-25 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0039_alter_propertymanagementrent_base_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 25, 10, 16, 9, 574013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 25, 10, 16, 9, 564053, tzinfo=datetime.timezone.utc)),
        ),
    ]
