# Generated by Django 5.2.7 on 2025-10-25 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0041_alter_propertymanagementrent_listed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]

