# Generated by Django 5.2.7 on 2025-10-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0043_alter_propertymanagementrent_listed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='parking_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='parking_spaces',
            field=models.IntegerField(default=0),
        ),
    ]

