# Generated by Django 5.2.7 on 2025-10-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0044_alter_propertymanagementrent_parking_spaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='social_platform',
            field=models.CharField(choices=[('X', 'X'), ('Linkdin', 'Linkdin'), ('Instagram', 'Instagram'), ('Company Website', 'Company Website'), ('Other', 'Other')], default='Instagram', max_length=20),
        ),
    ]
