# Generated by Django 5.2.7 on 2025-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0045_alter_sociallinks_social_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementsale',
            name='company_name',
            field=models.CharField(blank=True, default='No Compay Tied', verbose_name='Company'),
        ),
    ]

