# Generated by Django 5.2.7 on 2025-10-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0046_propertymanagementsale_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagementsale',
            name='company_name',
        ),
        migrations.AddField(
            model_name='propertymanagementrent',
            name='company_uuid',
            field=models.CharField(blank=True, default='None', max_length=40, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='company_uuid',
            field=models.CharField(blank=True, default='None', max_length=40, verbose_name='Company'),
        ),
    ]
