# Generated by Django 5.2.7 on 2025-10-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0047_remove_propertymanagementsale_company_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
