# Generated by Django 5.2.7 on 2025-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0048_delete_messages_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='size',
            field=models.IntegerField(blank=True, default='300', verbose_name='size'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='size',
            field=models.IntegerField(blank=True, default='300', verbose_name='size'),
        ),
    ]

