# Generated by Django 5.2.7 on 2025-11-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0049_propertymanagementrent_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='size',
            field=models.IntegerField(blank=True, default=0, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='size',
            field=models.IntegerField(blank=True, default=0, verbose_name='size'),
        ),
    ]
