# Generated by Django 5.2.7 on 2025-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0050_alter_propertymanagementrent_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='state',
            field=models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos State', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='state',
            field=models.CharField(choices=[('Abia', 'Abia State'), ('Adamawa', 'Adamawa State'), ('Akwa ibom', 'Akwa Ibom State'), ('Anambra', 'Anambra State'), ('Bauchi', 'Bauchi State'), ('Bayelsa', 'Bayelsa State'), ('Benue', 'Benue State'), ('Borno', 'Borno State'), ('Cross river', 'Cross River State'), ('Delta', 'Delta State'), ('Ebonyi', 'Ebonyi State'), ('Edo', 'Edo State'), ('Ekiti', 'Ekiti State'), ('Enugu', 'Enugu State'), ('Gombe', 'Gombe State'), ('Imo', 'Imo State'), ('Jigawa', 'Jigawa State'), ('Kaduna', 'Kaduna State'), ('Kano', 'Kano State'), ('Kastina', 'Kastina State'), ('Kebbi', 'Kebbi State'), ('Kogi', 'Kogi State'), ('Kwara', 'Kwara State'), ('Lagos', 'Lagos State'), ('Nasawara', 'Nasarawa State'), ('Niger', 'Niger State'), ('Ogun', 'Ogun State'), ('Ondo', 'Ondo State'), ('Osun', 'Osun State'), ('Oyo', 'Oyo State'), ('Plateau', 'Plateau State'), ('Rivers', 'Rivers State'), ('Sokoto', 'Sokoto State'), ('Taraba', 'Taraba State'), ('Yobe', 'Yobe State'), ('Zamfara', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos', max_length=20),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='social_platform',
            field=models.CharField(choices=[('X', 'X'), ('linkedin', 'linkedin'), ('Instagram', 'Instagram'), ('Company Website', 'Company Website'), ('Other', 'Other')], default='Instagram', max_length=20),
        ),
    ]

