# Generated by Django 5.2.7 on 2025-11-06 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0051_propertymanagementrent_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
