# Generated by Django 5.2.7 on 2025-11-06 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0052_alter_propertymanagementrent_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]

