# Generated by Django 5.2.7 on 2025-11-06 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0053_alter_propertymanagementsale_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]

