# Generated by Django 5.2.7 on 2025-11-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0054_propertymanagementrent_last_reset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='agent_uuid',
            field=models.CharField(blank=True, default='None', max_length=36, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='agent_uuid',
            field=models.CharField(blank=True, default='None', max_length=36, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='company_uuid',
            field=models.CharField(blank=True, default='None', max_length=36, verbose_name='Company'),
        ),
    ]
