# Generated by Django 5.2.7 on 2025-11-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0055_propertymanagementrent_agent_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagementRentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=None, verbose_name='user_id')),
                ('inquires_check', models.IntegerField(default=None, verbose_name='Inquiries')),
                ('on_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_analytics', to='estate.propertymanagementrent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManagementSaleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=None, verbose_name='user_id')),
                ('inquires_check', models.IntegerField(default=None, verbose_name='Inquiries')),
                ('on_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_analytics', to='estate.propertymanagementsale')),
            ],
        ),
    ]

