# Generated by Django 5.2.7 on 2025-11-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0056_propertymanagementrentanalytics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymanagementrentanalytics',
            old_name='on_sale',
            new_name='on_lease',
        ),
    ]

