# Generated by Django 5.2.7 on 2025-11-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0057_rename_on_sale_propertymanagementrentanalytics_on_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistforrent',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='estate.propertymanagementrent'),
        ),
        migrations.AlterField(
            model_name='wishlistforsale',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='estate.propertymanagementsale'),
        ),
    ]
