# Generated by Django 5.2.7 on 2025-11-10 11:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0058_alter_wishlistforrent_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Client's Name")),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email to be contacted')),
                ('phone_no', models.CharField(verbose_name='Clients Phone Number')),
                ('property_intrested', models.IntegerField(verbose_name='Property in question')),
                ('inquiry_message', models.TextField(verbose_name='Client short mssg')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='time created')),
                ('company_uuid', models.CharField(blank=True, default=None, max_length=36, verbose_name='company uuid')),
                ('agent_id', models.CharField(blank=True, default=None, max_length=36, verbose_name='Agents uuid')),
                ('schedule_tour', models.DateField(default=django.utils.timezone.now, verbose_name='Date for viewing')),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted', models.BooleanField(default=False, verbose_name='Contacted?')),
                ('not_contacted', models.BooleanField(default=False, verbose_name='Not Contacted')),
                ('cold_lead', models.BooleanField(default=False, verbose_name='Not likely to buy')),
                ('hot_lead', models.BooleanField(default=False, verbose_name='Most likely to buy')),
                ('qualified', models.BooleanField(default=False, verbose_name='Can actually buy')),
                ('negotiation', models.BooleanField(default=False, verbose_name='Negotiating')),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, verbose_name='Agreed Price')),
                ('completed', models.BooleanField(default=False, verbose_name='Transaction Completed')),
                ('lost', models.BooleanField(default=False, verbose_name='Lead lost')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='estate.leadinfo')),
            ],
        ),
    ]

