# Generated by Django 5.2.7 on 2025-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0059_leadinfo_leadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinfo',
            name='contact_type',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Email', 'Email')], default='Whatsapp', verbose_name='Media to get in touch'),
        ),
    ]
