# Generated by Django 5.2.7 on 2025-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0060_leadinfo_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementrent',
            name='property_type',
            field=models.CharField(default='Rent', verbose_name='property Type'),
        ),
        migrations.AddField(
            model_name='propertymanagementsale',
            name='property_type',
            field=models.CharField(default='Sale', verbose_name='property Type'),
        ),
    ]
