# Generated by Django 5.2.7 on 2025-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0061_propertymanagementrent_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinfo',
            name='property_type',
            field=models.CharField(default='Sale', verbose_name='Property Type'),
        ),
    ]
