# Generated by Django 5.2.7 on 2025-11-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0062_leadinfo_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinfo',
            name='contact_type',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Email', 'Email'), ('Phone Call', 'Phone Call')], default='Whatsapp', verbose_name='Media to get in touch'),
        ),
    ]

