# Generated by Django 5.2.7 on 2025-11-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0063_alter_leadinfo_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinfo',
            name='property_name',
            field=models.CharField(default='Bungalow', verbose_name='Property Name'),
        ),
    ]

