# Generated by Django 5.2.7 on 2025-11-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0064_leadinfo_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstatus',
            name='agreed_price',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='cold_lead',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='hot_lead',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='negotiation',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='not_contacted',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='qualified',
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='status',
            field=models.CharField(choices=[('Contacted', 'Contacted'), ('Not Contacted', 'Not Contacted'), ('Cold Lead', 'Cold Lead'), ('Hot Lead', 'Hot Lead'), ('Qualified', 'Qualified'), ('Negotiation', 'Negotiation'), ('Agreed Prices', 'Agreed Prices'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='Not Contacted', verbose_name='Lead Status'),
        ),
        migrations.AlterField(
            model_name='propertymanagementrent',
            name='house_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Block of flats', 'Block of Flats'), ('Bungalow Design', 'Bungalow Design'), ('Conclusion', 'Conclusion'), ('Detached bungalow', 'Detached Bungalow'), ('Detached duplex', 'Detached Duplex'), ('Duplex', 'Duplex'), ('Detached houses', 'Detached Houses'), ('Duplex Design', 'Duplex Design'), ('Detached', 'Detached'), ('Detached House', 'Detached House'), ('Massionette', 'Masionette'), ('Mansion', 'Mansion'), ('Penthouse', 'Penthouse'), ('Semi detached duplex', 'Semi Detached Duplex'), ('Semi detached bungalow', 'Semi Detached Bungalow'), ('Terraced bungalow', 'Terraced Bungalow'), ('Terraced duplex', 'Terraced Duplexes'), ('Townhouse', 'Townhouse'), ('Terraced houses', 'Terraced houses'), ('Traditional houses', 'Traditional Houses'), ('Terrace', 'Terrace')], default='Bungalow', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertymanagementsale',
            name='house_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Block of flats', 'Block of Flats'), ('Bungalow Design', 'Bungalow Design'), ('Conclusion', 'Conclusion'), ('Detached bungalow', 'Detached Bungalow'), ('Detached duplex', 'Detached Duplex'), ('Duplex', 'Duplex'), ('Detached houses', 'Detached Houses'), ('Duplex Design', 'Duplex Design'), ('Detached', 'Detached'), ('Detached House', 'Detached House'), ('Massionette', 'Masionette'), ('Mansion', 'Mansion'), ('Penthouse', 'Penthouse'), ('Semi detached duplex', 'Semi Detached Duplex'), ('Semi detached bungalow', 'Semi Detached Bungalow'), ('Terraced bungalow', 'Terraced Bungalow'), ('Terraced duplex', 'Terraced Duplexes'), ('Townhouse', 'Townhouse'), ('Terraced houses', 'Terraced houses'), ('Traditional houses', 'Traditional Houses'), ('Terrace', 'Terrace')], default='Bungalow', max_length=30),
        ),
    ]
