# Generated by Django 5.2.7 on 2025-11-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0065_remove_leadstatus_agreed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinfo',
            name='stages',
            field=models.CharField(choices=[('New', 'New'), ('Potential Friend', 'Potential Friend'), ('True Friend', 'True Friend'), ('Contracted', 'Contracted'), ('Closed/Won', 'Closed/Won'), ('Dispsposition', 'Disposition')], default='New', verbose_name='Lead Stages'),
        ),
        migrations.AddField(
            model_name='leadinfo',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Not Contacted', 'Not Contacted'), ('Contact Attempt', 'Contact Attempt'), ('Cold Lead', 'Cold Lead'), ('Hot Lead', 'Hot Lead'), ('Warm Lead', 'Warm Lead'), ('Qualified', 'Qualified'), ('Unqualified', 'Unualified')], default='Not Contacted', verbose_name='Lead Status'),
        ),
        migrations.AddField(
            model_name='leadinfo',
            name='tags',
            field=models.CharField(default='None', verbose_name='tags'),
        ),
        migrations.DeleteModel(
            name='LeadStatus',
        ),
    ]

