# Generated by Django 5.2.7 on 2025-11-17 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0066_leadinfo_stages_leadinfo_status_leadinfo_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinfo',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='time updated'),
        ),
        migrations.AlterField(
            model_name='leadinfo',
            name='stages',
            field=models.CharField(choices=[('New', 'New'), ('Potential Friend', 'Potential Friend'), ('True Friend', 'True Friend'), ('Contracted', 'Contracted'), ('Closed/Won', 'Closed/Won'), ('Disposition', 'Disposition')], default='New', verbose_name='Lead Stages'),
        ),
        migrations.AlterField(
            model_name='leadinfo',
            name='status',
            field=models.CharField(choices=[('Contacted', 'Contacted'), ('Not Contacted', 'Not Contacted'), ('Contact Attempt', 'Contact Attempt'), ('Cold Lead', 'Cold Lead'), ('Warm Lead', 'Warm Lead'), ('Hot Lead', 'Hot Lead'), ('Qualified', 'Qualified'), ('Unqualified', 'Unqualified')], default='Not Contacted', verbose_name='Lead Status'),
        ),
    ]
