# Generated by Django 5.2.7 on 2025-11-17 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0067_leadinfo_date_updated_alter_leadinfo_stages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinfo',
            name='schedule_tour',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date for viewing'),
        ),
    ]
