# Generated by Django 5.2.7 on 2025-11-17 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0068_alter_leadinfo_schedule_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinfo',
            name='schedule_tour',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date for viewing'),
        ),
    ]
