# Generated by Django 5.2.7 on 2025-11-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0069_alter_leadinfo_schedule_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_information',
            name='personal_info',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='agent',
        ),
        migrations.AlterField(
            model_name='leadinfo',
            name='stages',
            field=models.CharField(choices=[('New', 'New Lead'), ('Potential Friend', 'Potential Friend'), ('True Friend', 'True Friend'), ('Contracted', 'Contracted'), ('Closed/Won', 'Closed/Won'), ('Disposition', 'Disposition')], default='New', verbose_name='Lead Stages'),
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
        migrations.DeleteModel(
            name='Agent_Information',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]

