# Generated by Django 5.2.7 on 2025-11-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0070_remove_agent_information_personal_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='propertyrentimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertymanagementsaleanalytics',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='propertysaleimage',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='wishlistforrent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistforrent',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlistforsale',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistforsale',
            name='user',
        ),
        migrations.DeleteModel(
            name='PropertyManagementRentAnalytics',
        ),
        migrations.DeleteModel(
            name='PropertyRentImage',
        ),
        migrations.DeleteModel(
            name='PropertyManagementRent',
        ),
        migrations.DeleteModel(
            name='PropertyManagementSaleAnalytics',
        ),
        migrations.DeleteModel(
            name='PropertyManagementSale',
        ),
        migrations.DeleteModel(
            name='PropertySaleImage',
        ),
        migrations.DeleteModel(
            name='WishlistForRent',
        ),
        migrations.DeleteModel(
            name='WishlistForSale',
        ),
    ]

