# Generated by Django 5.2.7 on 2025-12-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0071_delete_feedback_remove_propertyrentimage_property_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
