# Generated by Django 5.2.7 on 2025-12-30 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0072_delete_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinfo',
            name='lead_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='lead uuid'),
        ),
    ]

