# Generated by Django 5.2.7 on 2025-12-30 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0073_leadinfo_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinfo',
            name='lead_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='lead uuid'),
        ),
    ]
