# Generated by Django 5.2.7 on 2026-01-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0074_alter_leadinfo_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinfo',
            name='property_intrested',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Property in question'),
        ),
        migrations.AlterField(
            model_name='leadinfo',
            name='property_name',
            field=models.CharField(default=None, verbose_name='Property Name'),
        ),
        migrations.AlterField(
            model_name='leadinfo',
            name='property_type',
            field=models.CharField(default=None, verbose_name='Property Type'),
        ),
    ]

