# Generated by Django 6.0.3 on 2026-03-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0075_alter_leadinfo_property_intrested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinfo',
            name='agent_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='Agents uuid'),
        ),
        migrations.AlterField(
            model_name='leadinfo',
            name='company_uuid',
            field=models.CharField(blank=True, default=None, max_length=36, null=True, verbose_name='company uuid'),
        ),
    ]
