# Generated by Django 6.0.3 on 2026-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0076_alter_leadinfo_agent_id_alter_leadinfo_company_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadinfo",
            name="landlord_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=36,
                null=True,
                verbose_name="Landlord uuid",
            ),
        ),
    ]
