#Al the states the website encompasses

STATES=[
    ('AB', 'Abia State'),
    ('AD', 'Adamawa State'),
    ('AK', 'Akwa Ibom State'),
    ('AN', 'Anambra State'),
    ('BA', 'Bauchi State'),
    ('BY', 'Bayelsa State'),
    ('BE', 'Benue State'),
    ('BO', 'Borno State'),
    ('CR', 'Cross River State'),
    ('DE', 'Delta State'),
    ('EB', 'Ebonyi State'),
    ('ED', 'Edo State'),
    ('EK', 'Ekiti State'),
    ('EN', 'Enugu State'),
    ('GO', 'Gombe State'),  
    ('IM', 'Imo State'),
    ('JI', 'Jigawa State'),
    ('KD', 'Kaduna State'),
    ('KN', 'Kano State'),
    ('KT', 'Kastina State'),
    ('KE', 'Kebbi State'),
    ('KG', 'Kogi State'),
    ('KW', 'Kwara State'),
    ('LA', 'Lagos State'),
    ('NA', 'Nasarawa State'),
    ('NI', 'Niger State'),
    ('OG', 'Ogun State'),
    ('ON', 'Ondo State'),
    ('OS', 'Osun State'),
    ('OY', 'Oyo State'),
    ('PL', 'Plateau State'),
    ('RI', 'Rivers State'),
    ('SO', 'Sokoto State'),
    ('TA', 'Taraba State'),
    ('YO', 'Yobe State'),
    ('ZA', 'Zamfara State'),
    ('FCT', 'Abuja State'),
]


TYPE=[
    ('Detached duplex','Detached Duplex'),
    ('Terraced duplex','Terraced Duplexes'),
    ('Semi detached duplex','Semi Detached Duplex'),
    ('Conclusion','Conclusion'),
    ('Townhouse','Townhouse'),
    ('Bungalow','Bungalow'),
    ('Detached bungalow','Detached Bungalow'),
    ('Block of flats','Block of Flats'),
    ('Semi detached bungalow','Semi Detached Bungalow'),
    ('Terraced bungalow','Terraced Bungalow'),
    ('Duplex','Duplex'),
    ('Penthouse','Penthouse'),
    ('Detached houses','Detached Houses'),
    ('Terraced houses','Terraced houses'),
    ('Apartment','Apartment'),
    ('Traditional houses','Traditional Houses'),
    ('Mansion','Mansion'),
    ('Terrace','Terrace'),
    ('Duplex Design','Duplex Design'),
    ('Massionette', 'Masionette'),
    ('Bungalow Design','Bungalow Design'),
    ('Detached','Detached'),
    ('Detached House','Detached House'),
    
]

SOCIAL_LINKS=[
    ('X', 'X'),
    ('Linkdin', 'Linkdin'),
    ('Instagram', 'Instagram'),
    ('Other', 'Other')
]