# Generated by Django 5.2.7 on 2025-10-30 21:28

import companies.models
import django.db.models.deletion
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Registered Company Name')),
                ('legal_certificate', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Certificate of Incoperation')),
                ('year_established', models.PositiveSmallIntegerField(max_length=4, verbose_name='Year Established')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Company Email')),
                ('address', models.CharField(max_length=255, verbose_name='Company Adress')),
                ('service_areas', models.CharField(choices=[('AB', 'Abia State'), ('AD', 'Adamawa State'), ('AK', 'Akwa Ibom State'), ('AN', 'Anambra State'), ('BA', 'Bauchi State'), ('BY', 'Bayelsa State'), ('BE', 'Benue State'), ('BO', 'Borno State'), ('CR', 'Cross River State'), ('DE', 'Delta State'), ('EB', 'Ebonyi State'), ('ED', 'Edo State'), ('EK', 'Ekiti State'), ('EN', 'Enugu State'), ('GO', 'Gombe State'), ('IM', 'Imo State'), ('JI', 'Jigawa State'), ('KD', 'Kaduna State'), ('KN', 'Kano State'), ('KT', 'Kastina State'), ('KE', 'Kebbi State'), ('KG', 'Kogi State'), ('KW', 'Kwara State'), ('LA', 'Lagos State'), ('NA', 'Nasarawa State'), ('NI', 'Niger State'), ('OG', 'Ogun State'), ('ON', 'Ondo State'), ('OS', 'Osun State'), ('OY', 'Oyo State'), ('PL', 'Plateau State'), ('RI', 'Rivers State'), ('SO', 'Sokoto State'), ('TA', 'Taraba State'), ('YO', 'Yobe State'), ('ZA', 'Zamfara State'), ('FCT', 'Abuja State')], default='Lagos', max_length=20)),
                ('area_specialization', models.CharField(max_length=50, verbose_name='Area of specialization')),
                ('company_bio', models.TextField(max_length=2000, unique=True, verbose_name='Brief Company Overview')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=companies.models.company_logo_path, validators=[core.validators.validate_image], verbose_name='Company Logo')),
                ('principal_broker', models.CharField(max_length=100, verbose_name='Registered Owner of Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_platform', models.CharField(choices=[('X', 'X'), ('Linkdin', 'Linkdin'), ('Instagram', 'Instagram'), ('Company Website', 'Company Website'), ('Other', 'Other')], default='Company Website', max_length=20)),
                ('link_to_social', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='companies.companyinformation')),
            ],
            options={
                'unique_together': {('social_platform', 'link_to_social')},
            },
        ),
    ]
