# Generated by Django 5.2.7 on 2025-10-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='year_established',
            field=models.IntegerField(max_length=4, verbose_name='Year Established'),
        ),
    ]
