# Generated by Django 5.2.7 on 2025-10-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyinformation_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='year_established',
            field=models.IntegerField(verbose_name='Year Established'),
        ),
    ]
