# Generated by Django 5.2.7 on 2025-10-30 22:47

import estate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyinformation_year_established'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='legal_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company/certificate', validators=[estate.validators.validate_file], verbose_name='Certificate of Incoperation'),
        ),
    ]
