# Generated by Django 5.2.7 on 2025-10-31 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companyinformation_legal_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='unique_user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='uuid'),
        ),
    ]

