# Generated by Django 5.2.7 on 2025-10-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_companyinformation_unique_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinformation',
            old_name='unique_user_id',
            new_name='unique_company_id',
        ),
    ]

