# Generated by Django 5.2.7 on 2025-11-03 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyinformation_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyanalytics',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]

