# Generated by Django 5.2.7 on 2025-11-06 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companyanalytics_last_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyanalytics',
            name='last_month_lease_views',
            field=models.IntegerField(default=0, verbose_name='last month lease views'),
        ),
        migrations.AddField(
            model_name='companyanalytics',
            name='last_month_profile_views',
            field=models.IntegerField(default=0, verbose_name='last month profile views'),
        ),
        migrations.AddField(
            model_name='companyanalytics',
            name='last_month_sale_views',
            field=models.IntegerField(default=0, verbose_name='last month sale views'),
        ),
        migrations.AlterField(
            model_name='companyanalytics',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last reset date'),
        ),
    ]

