# Generated by Django 5.2.7 on 2025-11-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_companyanalytics_last_month_lease_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyanalytics',
            name='last_month_lease_views',
            field=models.IntegerField(default=1, verbose_name='last month lease views'),
        ),
        migrations.AlterField(
            model_name='companyanalytics',
            name='last_month_profile_views',
            field=models.IntegerField(default=1, verbose_name='last month profile views'),
        ),
        migrations.AlterField(
            model_name='companyanalytics',
            name='last_month_sale_views',
            field=models.IntegerField(default=1, verbose_name='last month sale views'),
        ),
    ]
