# Generated by Django 5.2.7 on 2025-11-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companyanalytics_last_month_lease_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(default=None, verbose_name='user session id')),
                ('inquires_check', models.IntegerField(default=0, verbose_name='inq')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_id', to='companies.companyinformation')),
            ],
        ),
    ]
