# Generated by Django 5.2.7 on 2025-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyanalytics',
            name='competition',
            field=models.IntegerField(default=0, verbose_name='competition'),
        ),
    ]

