# Generated by Django 5.2.7 on 2025-11-21 15:30

import companies.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_companyanalytics_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified Company'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='legal_certificate',
            field=models.FileField(blank=True, null=True, upload_to=companies.models.company_file_path, validators=[core.validators.validate_file], verbose_name='Certificate of Incoperation'),
        ),
    ]

