# Generated by Django 5.2.7 on 2025-12-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_companyinformation_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinformation',
            name='area_specialization',
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Company Adress'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_bio',
            field=models.TextField(max_length=500, unique=True, verbose_name='Brief Company Overview'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Company Email'),
        ),
    ]
