# Generated by Django 5.2.7 on 2026-01-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_companyrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyanalytics',
            old_name='last_month_lease_views',
            new_name='average_lease_views',
        ),
        migrations.RenameField(
            model_name='companyanalytics',
            old_name='last_month_profile_views',
            new_name='average_profile_views',
        ),
        migrations.RenameField(
            model_name='companyanalytics',
            old_name='last_month_sale_views',
            new_name='average_sale_views',
        ),
    ]
