# Generated by Django 5.2.7 on 2026-01-31 15:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_rename_last_month_lease_views_companyanalytics_average_lease_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='Company ID')),
                ('company_uuid', models.CharField(default=uuid.UUID('be2d0d95-6eab-4ed5-a49b-581cdf03c993'), max_length=36, verbose_name='Company UUID')),
                ('job_title', models.CharField(default='Relator', max_length=100, null=True, verbose_name='Job Title')),
                ('job_type', models.CharField(default='Full Time', max_length=20, verbose_name='Full/Part time')),
                ('job_location', models.CharField(default='Remote', max_length=11, verbose_name='Location')),
                ('short_description', models.CharField(default=None, max_length=250, verbose_name='Short Desc')),
                ('full_description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Full Desc')),
                ('min_pay', models.FloatField(blank=True, default=None, null=True, verbose_name='Min Salary')),
                ('max_pay', models.FloatField(blank=True, default=None, null=True, verbose_name='Max Salary')),
                ('date_posted', models.DateField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('date_updated', models.DateField(default=django.utils.timezone.now, verbose_name='Date Updated')),
            ],
        ),
    ]

