# Generated by Django 5.2.7 on 2026-01-31 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='applicants',
            field=models.IntegerField(blank=True, default=0, verbose_name='Applicants Number'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='pending_applicants',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pending'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='shortlisted',
            field=models.IntegerField(blank=True, default=0, verbose_name='Shortlisted Number'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_uuid',
            field=models.CharField(default=uuid.UUID('0da74196-a7f1-4fe3-a4a7-4f5e733ccc07'), max_length=36, verbose_name='Company UUID'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(default='', max_length=11, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='', max_length=20, verbose_name='Full/Part time'),
        ),
    ]

