# Generated by Django 5.2.7 on 2026-01-31 20:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_jobpost_applicants_jobpost_pending_applicants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Application Deadline'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='benefits',
            field=models.TextField(blank=True, help_text='e.g., Health insurance, Remote work, etc.', null=True, verbose_name='Benefits & Perks'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='education_required',
            field=models.CharField(blank=True, help_text="e.g., Bachelor's Degree, High School, etc.", max_length=100, null=True, verbose_name='Education Required'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_required',
            field=models.CharField(blank=True, help_text='e.g., 2-5 years, Entry Level, Senior', max_length=50, null=True, verbose_name='Experience Required'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this job posting currently active?', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this job on homepage', verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='positions_available',
            field=models.IntegerField(default=1, help_text='How many people are you hiring?', verbose_name='Number of Positions'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='List of main job responsibilities', null=True, verbose_name='Key Responsibilities'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_currency',
            field=models.CharField(blank=True, default='NGN', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_period',
            field=models.CharField(choices=[('Hourly', 'Per Hour'), ('Daily', 'Per Day'), ('Weekly', 'Per Week'), ('Monthly', 'Per Month'), ('Yearly', 'Per Year')], default='Monthly', max_length=20, verbose_name='Salary Period'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_required',
            field=models.TextField(blank=True, help_text='Comma-separated list of required skills', null=True, verbose_name='Skills Required'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Company UUID'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Full Desc'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(default='', max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='max_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Salary'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='min_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Salary'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='short_description',
            field=models.CharField(default='', max_length=250, verbose_name='Short Desc'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_uuid', models.CharField(default=uuid.uuid4, verbose_name='applicant_uuid')),
                ('applicants_resume', models.FileField(blank=True, null=True, upload_to='', verbose_name='Applicants Resume')),
                ('date_posted', models.DateField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('date_updated', models.DateField(default=django.utils.timezone.now, verbose_name='Date Updated')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='companies.jobpost')),
            ],
        ),
    ]

