# Generated by Django 5.2.7 on 2026-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_jobpost_options_jobpost_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='agents_employed',
            field=models.IntegerField(default=0, verbose_name='Number of Employees'),
        ),
    ]
