# Generated by Django 6.0.3 on 2026-03-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_companyactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('company_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agent Department')),
                ('company_role', models.CharField(max_length=50, verbose_name='Agent Role')),
                ('agent_email', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Agent Email')),
                ('agent_phone_no', models.CharField(max_length=12, verbose_name='Phone No')),
                ('agent_uuid', models.CharField(max_length=36, unique=True, verbose_name='Agent UUID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('agent_status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Home Sick', 'Home Sick'), ('Parternity Leave', 'Parternity Leave'), ('Emergency', 'Emergency'), ('Resigned', 'Resigned'), ('On Probation', 'On probation'), ('Fired', 'Fired')], default='Active')),
                ('agent_headshot', models.ImageField(blank=True, upload_to='', verbose_name='Agent Picture')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='companies.companyinformation')),
            ],
        ),
    ]
