# Generated by Django 6.0.3 on 2026-03-15 17:50

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Link UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 3, 16, 17, 49, 59, 988104, tzinfo=datetime.timezone.utc), verbose_name='Date To expire')),
                ('max_uses', models.IntegerField(blank=True, default=None, null=True, verbose_name='Usage Possibility')),
                ('use_count', models.IntegerField(default=0, verbose_name='Use Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Link Active?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_link', to='companies.companyinformation')),
            ],
        ),
    ]
