# Generated by Django 6.0.3 on 2026-03-16 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_invitelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 16, 2, 54, 112834, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
