# Generated by Django 6.0.3 on 2026-03-16 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 17, 32, 50, 333391, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='max_uses',
            field=models.IntegerField(blank=True, default=200, null=True, verbose_name='Usage Possibility'),
        ),
    ]
