# Generated by Django 6.0.3 on 2026-03-17 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_alter_invitelink_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 18, 11, 48, 17, 922321, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
