# Generated by Django 6.0.3 on 2026-03-17 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 18, 14, 31, 39, 177095, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]

