# Generated by Django 6.0.3 on 2026-03-18 21:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinformation',
            name='agents_employed',
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 19, 21, 39, 25, 857727, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
        migrations.CreateModel(
            name='CompanyAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.CharField(default=None, max_length=100, verbose_name='Announcemt')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_announcements', to='companies.companyinformation')),
            ],
        ),
    ]

