# Generated by Django 6.0.3 on 2026-03-18 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_remove_companyinformation_agents_employed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 19, 23, 13, 41, 75931, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
