# Generated by Django 6.0.3 on 2026-03-19 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 20, 12, 42, 9, 413306, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
