# Generated by Django 6.0.3 on 2026-03-21 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='company_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='inventory_slot',
            field=models.IntegerField(default=50, verbose_name='Inventory Slots'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='listing_slots',
            field=models.IntegerField(default=30, verbose_name='Listing Slots'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 12, 25, 53, 947318, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
