# Generated by Django 6.0.3 on 2026-03-21 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_companyinformation_company_tier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinformation',
            old_name='inventory_slot',
            new_name='inventory_slots',
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 13, 47, 31, 293537, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
