# Generated by Django 6.0.3 on 2026-03-21 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_rename_inventory_slot_companyinformation_inventory_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 14, 9, 19, 192284, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]

