# Generated by Django 6.0.3 on 2026-03-22 19:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0039_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='companies.companyinformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 23, 19, 52, 14, 975482, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]

