# Generated by Django 6.0.3 on 2026-03-22 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_jobpost_company_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='Estate Web', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 23, 19, 55, 54, 846285, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]

