# Generated by Django 6.0.3 on 2026-03-23 12:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_jobpost_company_name_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrating',
            name='average_inquiries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='average_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='last_month_inquiries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='last_month_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyrating',
            name='period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 24, 12, 23, 27, 628682, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
