# Generated by Django 6.0.3 on 2026-03-23 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_companyrating_average_inquiries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyanalytics',
            name='average_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyanalytics',
            name='average_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyanalytics',
            name='monthly_leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyanalytics',
            name='monthly_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 24, 12, 42, 56, 139700, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]

