# Generated by Django 6.0.3 on 2026-03-23 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_companyanalytics_average_leads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 24, 16, 30, 28, 2278, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
