# Generated by Django 6.0.3 on 2026-03-24 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0044_alter_invitelink_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 25, 12, 40, 36, 392170, tzinfo=datetime.timezone.utc), verbose_name='Date To expire'),
        ),
    ]
