# Generated by Django 6.0.3 on 2026-03-27 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0049_alter_invitelink_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 28, 12, 18, 10, 35875, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date To expire",
            ),
        ),
    ]
