# Generated by Django 6.0.3 on 2026-03-30 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0050_alter_invitelink_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 31, 12, 46, 5, 138511, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date To expire",
            ),
        ),
    ]
