# Generated by Django 6.0.3 on 2026-03-30 12:54

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0052_alter_invitelink_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitelink",
            name="expires_at",
            field=models.DateTimeField(
                default=companies.models.InviteLink.default_expiry,
                verbose_name="Date To expire",
            ),
        ),
    ]
