# Generated by Django 6.0.3 on 2026-04-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0053_alter_invitelink_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinformation",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="companyinformation",
            name="users",
        ),
        migrations.AddField(
            model_name="companyinformation",
            name="user",
            field=models.ForeignKey(
                default=50,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
