# Generated by Django 6.0.3 on 2026-04-11 13:55

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0054_remove_companyinformation_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinformation",
            name="is_company_email_verified",
            field=models.BooleanField(
                default=False, verbose_name="Company Email Verified?"
            ),
        ),
        migrations.AddField(
            model_name="companyinformation",
            name="verification_token",
            field=models.CharField(
                default=companies.models.generate_invite_code, max_length=8, unique=True
            ),
        ),
    ]
