# Generated by Django 6.0.3 on 2026-04-12 22:49

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0055_companyinformation_is_company_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinformation",
            name="verification_token",
            field=models.CharField(
                blank=True,
                default=companies.models.generate_invite_code,
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
    ]
