# Generated by Django 6.0.3 on 2026-04-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0056_alter_companyinformation_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinformation",
            name="company_tier",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("growth", "Growth"),
                    ("enterprise", "Enterprise"),
                ],
                default="growth",
            ),
        ),
        migrations.AlterField(
            model_name="companyinformation",
            name="inventory_slots",
            field=models.IntegerField(default=100, verbose_name="Inventory Slots"),
        ),
        migrations.AlterField(
            model_name="companyinformation",
            name="listing_slots",
            field=models.IntegerField(default=55, verbose_name="Listing Slots"),
        ),
    ]
