# Generated by Django 6.0.3 on 2026-04-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0057_alter_companyinformation_company_tier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinformation",
            name="company_tier",
        ),
        migrations.RemoveField(
            model_name="companyinformation",
            name="inventory_slots",
        ),
        migrations.RemoveField(
            model_name="companyinformation",
            name="listing_slots",
        ),
    ]
