# Generated by Django 5.2.7 on 2025-10-31 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, verbose_name='uuid'),
        ),
    ]
