# Generated by Django 5.2.7 on 2025-10-31 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_unique_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='uuid'),
        ),
    ]
