# Generated by Django 6.0.3 on 2026-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_user_unique_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('company', 'Company'), ('landlord', 'Landlord')], default='customer', max_length=10),
        ),
    ]
